#include "config/ParamContainerTable.hh"
#include "training_data/GenTrainingData.hh"

#include <iostream>
#include <string>

#include "TFile.h"
#include "TTree.h"

using namespace std;

void PrintUsage()
{
    cout << "Usage : gen_training_data <prefix> [<parameter configure name> = parameters/config.txt]" << endl;
    cout << "   output data files will be named <prefix>.root <prefix>_input.dat and <prefix>_output.dat" << endl;
}

// this program read root file generated by pad_charges.mac Geant4 macro and generate traning data file.
int main(int argc, char **argv)
{

    string prefix, parFileName = "parameters/config.txt";
    if(argc == 2)
        prefix = argv[1];
    else if(argc == 3)
    {
        prefix = argv[1];
        parFileName = argv[2];
    }
    else
        PrintUsage();
             
    ParamContainerTable::GetBuilder()->BuildFromConfigFile(parFileName);
    ParamContainerTable::Instance()->DumpTable();

    GenTrainingData genTrain("pad_charges_evt.root", "pad_charges_bg.root");
    genTrain.SetNtrkSecondaryMax(3);
    genTrain.WriteTrainingData(prefix + "_input.dat", prefix + "_output.dat");
    return -1;
}