#include "config/ParamContainerTable.hh"
#include "training_data/GenTrainingData.hh"

#include <iostream>
#include <string>

#include "TFile.h"
#include "TTree.h"

using namespace std;

void PrintUsage()
{
    cout << "Usage : gen_training_data <prefix> <evt root file> <bg root file> [<parameter configure name> = parameters/config.txt]" << endl;
    cout << "   output data files will be named <prefix>_input.dat and <prefix>_output.dat" << endl;
}

// this program read root file generated by pad_charges.mac Geant4 macro and generate traning data file.
int main(int argc, char **argv)
{

    string prefix, evtFile, bgFile, parFileName = "parameters/config.txt";

    if(argc < 4 && argc > 5)
    {
        PrintUsage();
        return -1;
    }
    else if(argc == 5)
        parFileName = argv[4];
    prefix = argv[1];
    evtFile = argv[2];
    bgFile = argv[3];
             
    ParamContainerTable::GetBuilder()->BuildFromConfigFile(parFileName);
    ParamContainerTable::Instance()->DumpTable();

    GenTrainingData genTrain(evtFile, bgFile);
    genTrain.SetNtrkSecondaryMax(3);
    genTrain.WriteTrainingData(prefix + "_input.dat", prefix + "_output.dat");
    return -1;
}