# This macro must be executed in vis UI session.

# primary partice setting
/gun/particle ion
/gun/ion 6 12 2
/gun/energy 10 MeV

/attpc/gun/setPosX 0 mm
/attpc/gun/setPosY -50. mm
/attpc/gun/setPosZ -300. mm

/attpc/gas/setBeamPipePosY -50. mm

/attpc/field/value 2.5
/attpc/gasChamber/activateHitTuple false
/attpc/gasChamber/activateDigiTuple false
/attpc/output/activate false

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/invert true
/vis/scene/endOfRunAction accumulate

/attpc/process/CarbonAlpha/forceByTrackLen 280 mm
/run/beamOn 1

/attpc/process/CarbonAlpha/forceByTrackLen 10 km
/gun/number 10
/run/beamOn 1