# This macro must be executed in vis UI session.

# primary partice setting
/gun/particle ion
/gun/ion 6 12 2
/gun/energy 10 MeV

/attpc/gun/setPosX 0 mm
/attpc/gun/setPosY -50. mm
/attpc/gun/setPosZ -300. mm

/attpc/geometry/setBeamPipePosY -50. mm

/attpc/field/bField 2.5 0 0 tesla
/attpc/gas/setMixture He 90 iC4H10 10
/attpc/gas/setPressure 0.1 atm
/attpc/gasChamber/activateHitTuple false
/attpc/gasChamber/activateDigiTuple false
/attpc/output/activate false

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/invert true
/vis/scene/endOfRunAction accumulate

/attpc/process/CarbonAlpha/forceAtRndmTrkLenUniform 0 100
/run/beamOn 1

/attpc/process/CarbonAlpha/activate false
/gun/number 10
/run/beamOn 1

/vis/viewer/flush
