# primary partice setting
/gun/particle ion
/gun/ion 6 12 2
/gun/energy 6 MeV

/attpc/gun/setPosX 0 mm
/attpc/gun/setPosY -50. mm
/attpc/gun/setPosZ -300. mm

/attpc/geometry/setBeamPipePosY -50. mm

/attpc/field/bField 2.5 0 0 tesla
/attpc/output/activate true

/attpc/gas/setStepLimit 0.05 mm

/attpc/gasChamber/activateHitTuple false
/control/alias prefix test

# simulate the case with interested events(Alpha capture)
/attpc/process/CarbonAlpha/forceAtRndmTrkLenUniform 0 110
/attpc/output/setFileName {prefix}_evt1.root
/run/beamOn 15000

# simulate the case with no interested events(No alpha capture)
/attpc/process/CarbonAlpha/activate false
/attpc/output/setFileName {prefix}_evt2.root
/run/beamOn 15000

/attpc/output/mergeFiles {prefix}_evt.root {prefix}_evt1.root {prefix}_evt2.root 

# backgrounds
/attpc/process/CarbonAlpha/activate false
/attpc/output/setFileName {prefix}_bg.root
/gun/number 10
/run/beamOn 30000